code --install-extension vscode-icons
code --install-extension vscodevim.vim
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension rangav.vscode-thunder-client
code --install-extension esbenp.prettier-vscode
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension TabNine.tabnine-vscode
code --install-extension 2gua.rainbow-brackets
code --install-extension oderwat.indent-rainbow
code --install-extension stuart.unique-window-colors
code --install-extension eamodio.gitlens
code --install-extension ChakrounAnas.turbo-console-log
code --install-extension yzhang.markdown-all-in-one
code --install-extension sukumo28.wav-preview